### ISSUE TITLE
Input jumbles up with coc_outline

### ISSUE THREAD

**Issue by Galicarnax** [vn-ki/coc-clap#3] opened 2020-04-19 09:19 UTC
When I call `Clap coc_outline` and begin typing text, the first letter somehow moves after the cursor, and so ends up at the end of the input, rather than at its beginning. E.g., if I  want to type `foobar`, I end up with `oobarf`. Other lists (`coc_extensions`, `coc_commands`,...) don't seem to have this problem.

**Comment by vn-ki** [comment] 2020-04-19 10:06
@liuchengxu Any insight into this?

**Comment by liuchengxu** [comment] 2020-04-19 10:13
Can you describe your environment and provide a way to reproduce this? I don't see this locally. @Galicarnax

**Comment by Galicarnax** [comment] 2020-04-19 11:09
Using neovim v. 0.4.3. Have installed both `vim-clap` and `coc-clap` with vim-plug. Basically, that's all, as much as my init.vim is concerned (ok, I also have `let g:clap_insert_mode_only = v:true`) and `autocmd User ClapOnExit call lightline#update()`, but these do not seem to matter). As I said, every clap list I have tried so far works normally. It is only if I call `Clap coc_outline`, the first letter typed into clap's input filed appears _after_ cursor, and only the next typed letters follow after cursor, as expected. This reproduces in my cases always with `Clap coc_outline`, no matter if I call directly from the command line or via a key map.

**Comment by liuchengxu** [comment] 2020-04-19 11:39
Can't help more as I can't reproduce. You could see if something is wrong with `source` of outline. Apply the following patch and see if the problem persists.

```diff
diff --git a/autoload/clap/provider/coc_outline.vim b/autoload/clap/provider/coc_outline.vim
index 0f3572d..cc4c2ab 100644
--- a/autoload/clap/provider/coc_outline.vim
+++ b/autoload/clap/provider/coc_outline.vim
@@ -4,6 +4,7 @@
 let s:outline = {}

 function! s:outline.source() abort
+  return ['dummy outline']
   let l:bufnr = bufnr('')

   execute 'keepalt buffer' g:clap.start.bufnr
```

**Comment by vn-ki** [comment] 2020-04-19 11:45
I can actually reproduce this on `Clap files` with vim

![image](https://user-images.githubusercontent.com/31964688/79686905-5358f980-8261-11ea-9701-15a0532c1a2c.png)

I think it is a Clap bug. @liuchengxu

**Comment by vn-ki** [comment] 2020-04-19 11:47
Oh, I think the bug mentioned here is different. But the one mentioned above is a real bug. I don't mind it much because i don't use vim and this does not exist in neovim.

Also @Galicarnax maybe using neovim master might improve your situation ?

**Comment by Galicarnax** [comment] 2020-04-19 11:58
> Can't help more as I can't reproduce. You could see if something is wrong with `source` of outline. Apply the following patch and see if the problem persists.
> 
> ```diff
> diff --git a/autoload/clap/provider/coc_outline.vim b/autoload/clap/provider/coc_outline.vim
> index 0f3572d..cc4c2ab 100644
> --- a/autoload/clap/provider/coc_outline.vim
> +++ b/autoload/clap/provider/coc_outline.vim
> @@ -4,6 +4,7 @@
>  let s:outline = {}
> 
>  function! s:outline.source() abort
> +  return ['dummy outline']
>    let l:bufnr = bufnr('')
> 
>    execute 'keepalt buffer' g:clap.start.bufnr
> ```

After adding `return ['dummy outline']` the typing is normal, all letter follow cursor as they should (but, of course, nothing is shown in the list).

**Comment by liuchengxu** [comment] 2020-04-19 12:09
If the typing is good once the current implementation is removed, then `source` of outline could be the culprit. @Galicarnax @vn-ki 

@vn-ki See https://github.com/liuchengxu/vim-clap/pull/340#issue-381994360https://github.com/liuchengxu/vim-clap/pull/340#issue-381994360 and https://github.com/liuchengxu/vim-clap/pull/340#issuecomment-593067408. That issue is due to the wrong higlight offset of matched items. I can't reproduce it sadly.

**Comment by vn-ki** [comment] 2020-04-19 12:12
Okay, thanks for your help.

@Galicarnax since I can't reproduce your issue as well, can you please try neovim master?

**Comment by Galicarnax** [comment] 2020-04-19 12:12
But the way, just noted the problem with highlight as well. E.g., calling `Clap files` and typing `a`, a get the list where most items have only one `a` highlighted (even though they have more than one `a` each), and in some items even other letters are highlighted (e.g., `n`, `t`, ...).

**Comment by Galicarnax** [comment] 2020-04-19 12:16
> Okay, thanks for your help.
> 
> @Galicarnax since I can't reproduce your issue as well, can you please try neovim master?

I've installed nvim using pre-built releases. Do U imply I should clone the master branch and compile nvim myself?

**Comment by liuchengxu** [comment] 2020-04-19 12:16
@Galicarnax If you still see the highlight misorder issue, please file an issue at https://github.com/liuchengxu/vim-clap/issues.

**Comment by Galicarnax** [comment] 2020-04-19 12:30
@vn-ki So I have built the master neovim, no problem there. I'll stick to this version. Thanks.

**Comment by vn-ki** [comment] 2020-04-27 16:31
Closing because issue is resolved.

**Closed by vn-ki** 2020-04-27 16:31 UTC
